
package org.example.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BattleshipServer", targetNamespace = "http://example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BattleshipServer {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod(operationName = "ConnectPlayer")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConnectPlayer", targetNamespace = "http://example.org/", className = "org.example.service.ConnectPlayer")
    @ResponseWrapper(localName = "ConnectPlayerResponse", targetNamespace = "http://example.org/", className = "org.example.service.ConnectPlayerResponse")
    @Action(input = "http://example.org/BattleshipServer/ConnectPlayerRequest", output = "http://example.org/BattleshipServer/ConnectPlayerResponse")
    public int connectPlayer();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFirstTable", targetNamespace = "http://example.org/", className = "org.example.service.GetFirstTable")
    @ResponseWrapper(localName = "getFirstTableResponse", targetNamespace = "http://example.org/", className = "org.example.service.GetFirstTableResponse")
    @Action(input = "http://example.org/BattleshipServer/getFirstTableRequest", output = "http://example.org/BattleshipServer/getFirstTableResponse")
    public List<Integer> getFirstTable();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSecondTable", targetNamespace = "http://example.org/", className = "org.example.service.GetSecondTable")
    @ResponseWrapper(localName = "getSecondTableResponse", targetNamespace = "http://example.org/", className = "org.example.service.GetSecondTableResponse")
    @Action(input = "http://example.org/BattleshipServer/getSecondTableRequest", output = "http://example.org/BattleshipServer/getSecondTableResponse")
    public List<Integer> getSecondTable();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLastPlayerMove", targetNamespace = "http://example.org/", className = "org.example.service.GetLastPlayerMove")
    @ResponseWrapper(localName = "getLastPlayerMoveResponse", targetNamespace = "http://example.org/", className = "org.example.service.GetLastPlayerMoveResponse")
    @Action(input = "http://example.org/BattleshipServer/getLastPlayerMoveRequest", output = "http://example.org/BattleshipServer/getLastPlayerMoveResponse")
    public int getLastPlayerMove();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLastMove", targetNamespace = "http://example.org/", className = "org.example.service.GetLastMove")
    @ResponseWrapper(localName = "getLastMoveResponse", targetNamespace = "http://example.org/", className = "org.example.service.GetLastMoveResponse")
    @Action(input = "http://example.org/BattleshipServer/getLastMoveRequest", output = "http://example.org/BattleshipServer/getLastMoveResponse")
    public int getLastMove();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCur", targetNamespace = "http://example.org/", className = "org.example.service.GetCur")
    @ResponseWrapper(localName = "getCurResponse", targetNamespace = "http://example.org/", className = "org.example.service.GetCurResponse")
    @Action(input = "http://example.org/BattleshipServer/getCurRequest", output = "http://example.org/BattleshipServer/getCurResponse")
    public int getCur();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setCur", targetNamespace = "http://example.org/", className = "org.example.service.SetCur")
    @ResponseWrapper(localName = "setCurResponse", targetNamespace = "http://example.org/", className = "org.example.service.SetCurResponse")
    @Action(input = "http://example.org/BattleshipServer/setCurRequest", output = "http://example.org/BattleshipServer/setCurResponse")
    public void setCur(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "makeMove", targetNamespace = "http://example.org/", className = "org.example.service.MakeMove")
    @ResponseWrapper(localName = "makeMoveResponse", targetNamespace = "http://example.org/", className = "org.example.service.MakeMoveResponse")
    @Action(input = "http://example.org/BattleshipServer/makeMoveRequest", output = "http://example.org/BattleshipServer/makeMoveResponse")
    public void makeMove(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
